"""Adicionando modelo de avaliações

Revision ID: 038a49f1e8c1
Revises: 3ab48964eef8
Create Date: 2024-08-16 15:01:17.031363

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '038a49f1e8c1'
down_revision = '3ab48964eef8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('avaliacao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('produto_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('comentario', sa.Text(), nullable=False),
    sa.Column('estrelas', sa.Integer(), nullable=False),
    sa.Column('data_criado', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['produto_id'], ['addproduto.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('avaliacao')
    # ### end Alembic commands ###
