"""Add tamanho column to Addproduto

Revision ID: 4bfdf4e96e9a
Revises: ee47382f33ba
Create Date: 2024-08-16 19:07:52.568384

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4bfdf4e96e9a'
down_revision = 'ee47382f33ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('addproduto', schema=None) as batch_op:
        batch_op.alter_column('tamanho',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Text(),
               existing_nullable=False,
               existing_server_default=sa.text("'M'"))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('addproduto', schema=None) as batch_op:
        batch_op.alter_column('tamanho',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False,
               existing_server_default=sa.text("'M'"))

    # ### end Alembic commands ###
