from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6fb64acc0c0c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cadastrar', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_cadastrar_email', ['email'])
        batch_op.create_unique_constraint('uq_cadastrar_username', ['username'])

    with op.batch_alter_table('cliente_pedido', schema=None) as batch_op:
        batch_op.alter_column('total_pago',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cliente_pedido', schema=None) as batch_op:
        batch_op.alter_column('total_pago',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)

    with op.batch_alter_table('cadastrar', schema=None) as batch_op:
        batch_op.drop_constraint('uq_cadastrar_email', type_='unique')
        batch_op.drop_constraint('uq_cadastrar_username', type_='unique')

    # ### end Alembic commands ###
