"""Add Avaliacao model

Revision ID: 92a22449cc27
Revises: 6fb64acc0c0c
Create Date: 2024-08-15 23:47:13.763101

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '92a22449cc27'
down_revision = '6fb64acc0c0c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('avaliacao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('produto_id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('estrelas', sa.Integer(), nullable=False),
    sa.Column('comentario', sa.Text(), nullable=True),
    sa.Column('data_criado', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['cadastrar.id'], ),
    sa.ForeignKeyConstraint(['produto_id'], ['addproduto.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('avaliacao')
    # ### end Alembic commands ###
